services:
    _instanceof:
      DivanteTranslationBundle\Provider\ProviderInterface:
          arguments:
              $apiKey: '%divante_translation.api_key%'
              $fallbackApiKey: '%divante_translation.fallback_api_key%'
          tags: ['translation_bundle.provider']

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DivanteTranslationBundle\Controller\:
        resource: '../../Controller'
        public: true
        arguments:
            - '%divante_translation%'
        tags: ['controller.service_arguments']

    DivanteTranslationBundle\Provider\ProviderFactory:
        arguments: [!tagged translation_bundle.provider]
