name: Tests
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, json
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
